# Generated by Django 2.1.4 on 2018-12-04 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliations',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Countries'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='affiliation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Affiliations'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='experiments',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiment_creator', to='app.Contacts'),
        ),
        migrations.AlterField(
            model_name='experiments',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Instruments'),
        ),
        migrations.AlterField(
            model_name='experiments',
            name='local_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Contacts'),
        ),
        migrations.AlterField(
            model_name='experiments',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.InstrumentRequest'),
        ),
        migrations.AlterField(
            model_name='instrumentparameters',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.InstrumentParameterSets'),
        ),
        migrations.AlterField(
            model_name='instrumentrequest',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Instruments'),
        ),
        migrations.AlterField(
            model_name='instrumentrequest',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Options'),
        ),
        migrations.AlterField(
            model_name='instrumentrequest',
            name='propsal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Proposals'),
        ),
        migrations.AlterField(
            model_name='instruments',
            name='admins',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instrument_admins', to='app.Contacts'),
        ),
        migrations.AlterField(
            model_name='instruments',
            name='local_contacts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Contacts'),
        ),
        migrations.AlterField(
            model_name='instruments',
            name='parameter_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.InstrumentParameterSets'),
        ),
        migrations.AlterField(
            model_name='options',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Instruments'),
        ),
        migrations.AlterField(
            model_name='parametervalues',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.InstrumentParameters'),
        ),
        migrations.AlterField(
            model_name='parametervalues',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.InstrumentRequest'),
        ),
        migrations.AlterField(
            model_name='proposals',
            name='continuation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposal_continuation', to='app.Proposals'),
        ),
        migrations.AlterField(
            model_name='proposals',
            name='coproposers',
            field=models.ManyToManyField(blank=True, related_name='proposal_coporposals', to='app.Contacts'),
        ),
        migrations.AlterField(
            model_name='proposals',
            name='local_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposal_local_contact', to='app.Contacts'),
        ),
        migrations.AlterField(
            model_name='proposals',
            name='proposer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Contacts'),
        ),
        migrations.AlterField(
            model_name='proposals',
            name='publications',
            field=models.ManyToManyField(blank=True, to='app.Publications'),
        ),
        migrations.AlterField(
            model_name='proposals',
            name='resubmission',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='app.Proposals'),
        ),
        migrations.AlterField(
            model_name='proposals',
            name='samples',
            field=models.ManyToManyField(blank=True, to='app.Samples'),
        ),
        migrations.AlterField(
            model_name='proposals',
            name='scientific_bg',
            field=models.FileField(blank=True, upload_to='.'),
        ),
        migrations.AlterField(
            model_name='samplephotos',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Samples'),
        ),
        migrations.AlterField(
            model_name='sampleremarks',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Contacts'),
        ),
        migrations.AlterField(
            model_name='sampleremarks',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Samples'),
        ),
        migrations.AlterField(
            model_name='samples',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Contacts'),
        ),
        migrations.AlterField(
            model_name='slots',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Contacts'),
        ),
        migrations.AlterField(
            model_name='slots',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Instruments'),
        ),
    ]
