# Generated by Django 2.1.4 on 2018-12-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181204_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposals',
            name='coproposers',
            field=models.ManyToManyField(blank=True, related_name='proposal_coporposals', to='app.Contacts'),
        ),
        migrations.AlterField(
            model_name='proposals',
            name='publications',
            field=models.ManyToManyField(blank=True, to='app.Publications'),
        ),
        migrations.AlterField(
            model_name='proposals',
            name='samples',
            field=models.ManyToManyField(blank=True, to='app.Samples'),
        ),
    ]
