# Generated by Django 2.1.4 on 2019-01-03 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181204_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'in preparation'), ('S', 'submitted'), ('U', 'user office checking'), ('T', 'technical review'), ('R', 'in panel review'), ('D', 'director approval'), ('A', 'accepted'), ('F', 'finished'), ('X', 'rejected')], max_length=1)),
                ('remarks', models.TextField(max_length=5000)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.AddField(
            model_name='proposals',
            name='proposaltype',
            field=models.CharField(choices=[('S', 'standard'), ('L', 'long-term'), ('P', 'proof of concept'), ('T', 'test')], default='S', max_length=1),
        ),
        migrations.AddField(
            model_name='status',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Proposals'),
        ),
        migrations.AddField(
            model_name='status',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Contacts'),
        ),
    ]
