# Generated by Django 2.1.4 on 2019-01-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_proposals_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposals',
            name='pid',
            field=models.CharField(default=None, editable=False, max_length=8, null=True),
        ),
    ]
