# Generated by Django 2.1.4 on 2019-01-04 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190103_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposals',
            name='proposer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('P', 'in preparation'), ('S', 'submitted'), ('U', 'user office checking'), ('T', 'in technical review'), ('R', 'in panel review'), ('D', 'by director'), ('A', 'accepted'), ('F', 'finished'), ('X', 'rejected')], max_length=1),
        ),
    ]
