# Generated by Django 2.1.5 on 2019-01-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190104_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposals',
            options={'ordering': ('-created',), 'permissions': (('change_status', 'Can set proposal to any status'), ('approve_technical', 'Can submit technical comments'), ('takeover_panel', 'Can put proposal to review'), ('approve_panel', 'Can submit panel decision'), ('approve_director', 'Can submit director approval'), ('finish_proposal', 'Can finish approved proposal'))},
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('P', 'in preparation'), ('S', 'submitted'), ('U', 'user office checking'), ('T', 'in technical review'), ('W', 'waiting for panel'), ('R', 'in panel review'), ('D', 'by director'), ('A', 'accepted'), ('F', 'finished'), ('X', 'rejected')], max_length=1),
        ),
    ]
