# Generated by Django 2.1.5 on 2019-01-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190118_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposals',
            name='continuation',
        ),
        migrations.RemoveField(
            model_name='proposals',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='proposals',
            name='resubmission',
        ),
        migrations.AddField(
            model_name='proposals',
            name='last_status',
            field=models.CharField(choices=[('P', 'in preparation'), ('S', 'submitted'), ('U', 'user office checking'), ('T', 'in technical review'), ('W', 'waiting for panel'), ('R', 'in panel review'), ('D', 'by director'), ('A', 'accepted'), ('F', 'finished'), ('X', 'rejected')], default='P', max_length=1),
        ),
    ]
