# Generated by Django 2.1.5 on 2019-01-30 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190128_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliations',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Countries'),
        ),
    ]
