# Generated by Django 2.1.5 on 2019-02-08 08:24

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190130_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposals',
            name='scientific_bg',
            field=models.FileField(blank=True, null=True, upload_to='userpdf', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), app.models.validate_pdf_lenth]),
        ),
    ]
