# Generated by Django 2.1.5 on 2019-02-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190208_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='hiddenremarks',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='status',
            name='remarks',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
