# Generated by Django 2.1.5 on 2019-02-13 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20190212_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ('-date',), 'permissions': (('see_hidden_remarks', 'Can see hidden remarks of whole status history'),)},
        ),
        migrations.RenameField(
            model_name='status',
            old_name='hiddenremarks',
            new_name='hiddenremark',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='remarks',
            new_name='remark',
        ),
    ]
