# Generated by Django 2.1.5 on 2019-02-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190213_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='hiddenremark',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='status',
            name='remark',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
    ]
