# Generated by Django 2.1.5 on 2019-02-14 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20190214_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposals',
            name='student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposals',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposal_supervisor', to='app.Contacts'),
        ),
    ]
