# Generated by Django 2.1.5 on 2019-02-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20190214_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
