# Generated by Django 2.2 on 2019-05-17 16:44

from django.db import models, migrations

def forward(apps, schema_editor):
    Proposals = apps.get_model("app", "Proposals")
    for proposal in Proposals.objects.all():
        proposal.local_contacts.add(proposal.local_contact)

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20190517_1838'),
    ]

    operations = [
        migrations.RunPython(forward)
]
