# Generated by Django 2.2.2 on 2019-06-12 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_proposals_local_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumentrequest',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='instrumentrequest',
            name='option',
        ),
        migrations.RemoveField(
            model_name='instrumentrequest',
            name='propsal',
        ),
        migrations.RemoveField(
            model_name='instrumentrequest',
            name='shared_options',
        ),
        migrations.RemoveField(
            model_name='parametervalues',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='parametervalues',
            name='request',
        ),
        migrations.RemoveField(
            model_name='slots',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='slots',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='experiments',
            name='finalized',
        ),
        migrations.RemoveField(
            model_name='experiments',
            name='request',
        ),
        migrations.RemoveField(
            model_name='instruments',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='instruments',
            name='local_contacts',
        ),
        migrations.RemoveField(
            model_name='instruments',
            name='parameter_set',
        ),
        migrations.RemoveField(
            model_name='instruments',
            name='time_to_schedule',
        ),
        migrations.AddField(
            model_name='experiments',
            name='option',
            field=models.ManyToManyField(blank=True, to='app.Options'),
        ),
        migrations.AddField(
            model_name='experiments',
            name='proposal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='app.Proposals'),
        ),
        migrations.AddField(
            model_name='experiments',
            name='shared_options',
            field=models.ManyToManyField(blank=True, to='app.SharedOptions'),
        ),
        migrations.AlterField(
            model_name='instruments',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='options',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='InstrumentParameters',
        ),
        migrations.DeleteModel(
            name='InstrumentParameterSets',
        ),
        migrations.DeleteModel(
            name='InstrumentRequest',
        ),
        migrations.DeleteModel(
            name='ParameterValues',
        ),
        migrations.DeleteModel(
            name='Slots',
        ),
    ]
