# Generated by Django 2.2.2 on 2019-06-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20190612_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruments',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='instrument_admins', to='app.Contacts'),
        ),
    ]
