# Generated by Django 2.2.2 on 2019-06-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_instruments_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiments',
            name='duration',
            field=models.DurationField(editable=False),
        ),
    ]
