# Generated by Django 2.2.2 on 2019-06-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20190614_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruments',
            name='book_by_hour',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='affiliations',
            name='address1',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='affiliations',
            name='address2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='affiliations',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='affiliations',
            name='department',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
