# Generated by Django 2.2.2 on 2019-06-25 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20190618_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruments',
            name='admins',
        ),
        migrations.CreateModel(
            name='InstrumentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(blank=True, related_name='instrument_admins', to='app.Contacts')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='instruments',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.InstrumentGroup'),
        ),
    ]
