# Generated by Django 2.2.2 on 2019-07-05 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20190625_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiments',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='experiment_responsible', to='app.Contacts'),
        ),
        migrations.AlterField(
            model_name='experiments',
            name='local_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiment_lc', to='app.Contacts'),
        ),
    ]
