# Generated by Django 2.2.2 on 2019-08-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20190705_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumentgroup',
            name='users',
        ),
        migrations.AddField(
            model_name='instrumentgroup',
            name='trained_users',
            field=models.ManyToManyField(blank=True, related_name='trained_instrumentgroups', to='app.Contacts'),
        ),
    ]
