# Generated by Django 2.2.2 on 2019-08-08 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20190808_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruments',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instruments', to='app.InstrumentGroup'),
        ),
    ]
