# Generated by Django 2.2.2 on 2019-12-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20190809_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
