# Generated by Django 2.2.2 on 2019-12-13 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_contacts_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiments',
            name='shared_options',
        ),
        migrations.CreateModel(
            name='SharedOptionSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('duration', models.DurationField(editable=False)),
                ('experiment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='app.Experiments')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
