# Generated by Django 2.2.2 on 2019-12-16 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_sharedoptionslot_shared_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedoptionslot',
            name='experiment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Experiments'),
        ),
    ]
