# Generated by Django 3.0.2 on 2020-01-23 14:39

import app.models
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20200114_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='userpdf', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), app.models.validate_pdf_lenth])),
                ('year', models.PositiveIntegerField(default=2020)),
                ('deadline', models.DateTimeField(default=datetime.datetime(2020, 3, 23, 14, 39, 22, 351456))),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Proposals')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
