# Generated by Django 3.0.4 on 2020-03-18 14:24

import datetime
from django.db import migrations, models

def forward(apps, schema_editor):
    Proposals = apps.get_model("app", "Proposals")
    for proposal in Proposals.objects.filter(proposaltype__in = 'SL'):
        proposal.review_process = 'P'
        proposal.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposals',
            name='review_process',
            field=models.CharField(choices=[('P', 'panel'), ('B', 'board'), ('N', 'none')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='proposals',
            name='last_status',
            field=models.CharField(choices=[('P', 'in preparation'), ('S', 'submitted'), ('U', 'user office checking'), ('T', 'technical check'), ('E', 'technical check'), ('B', 'board review'), ('W', 'waiting for panel'), ('R', 'in panel review'), ('D', 'by director'), ('A', 'accepted'), ('H', 'on hold'), ('F', 'finished'), ('X', 'rejected')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='report',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 17, 14, 24, 4, 659877)),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('P', 'in preparation'), ('S', 'submitted'), ('U', 'user office checking'), ('T', 'technical check'), ('E', 'technical check'), ('B', 'board review'), ('W', 'waiting for panel'), ('R', 'in panel review'), ('D', 'by director'), ('A', 'accepted'), ('H', 'on hold'), ('F', 'finished'), ('X', 'rejected')], max_length=1),
        ),
        migrations.RunPython(forward),
    ]
