# Generated by Django 3.0.4 on 2020-03-18 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20200318_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposals',
            name='review_process',
            field=models.CharField(choices=[('P', 'panel'), ('B', 'board'), ('N', 'none')], default='N', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='report',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 17, 14, 39, 9, 376737)),
        ),
    ]
