# Generated by Django 3.0.4 on 2020-03-18 23:21

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20200318_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposals',
            options={'ordering': ('-created',), 'permissions': (('change_status', 'Can set proposal to any status, edit proposal type anytime'), ('approve_technical', 'Can submit technical comments'), ('takeover_panel', 'Can assign a reviewer and submit any review'), ('approve_panel', 'Can submit panel decision'), ('approve_board', 'Can submit board decision'), ('view_panel_proposals', 'Can view panel related proposals'), ('view_board_proposals', 'Can view board related proposals'), ('approve_director', 'Can submit director approval'), ('finish_proposal', 'Can finish approved proposal'))},
        ),
    ]
