# Generated by Django 3.0.4 on 2020-03-18 23:27

from django.db import migrations
from django.contrib.auth.models import Group, Permission

def add_group_permissions(apps, schema_editor):
    # Criando Administrador
    group, created = Group.objects.get_or_create(name='board')
    if created:
        permissions_qs = Permission.objects.filter(
                         codename__in=['view_board_proposals',
                                       'approve_board',
                                       'see_hidden_remarks',]
        )
        group.permissions.set(permissions_qs)
        group.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20200318_2321'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions),
    ]
