# Generated by Django 3.0.6 on 2020-05-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20200318_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('link', models.URLField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('journal', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('citations', models.IntegerField(null=True)),
                ('issued', models.DateField(db_index=True, null=True)),
                ('full_citation', models.CharField(blank=True, max_length=2000, null=True)),
                ('authors', models.ManyToManyField(to='app.Contacts')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.DeleteModel(
            name='Publications',
        ),
        migrations.AlterField(
            model_name='proposals',
            name='publications',
            field=models.ManyToManyField(blank=True, to='app.Publication'),
        ),
    ]
