# Generated by Django 3.0.6 on 2020-06-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20200609_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='amount',
            field=models.FloatField(),
        ),
    ]
