# Generated by Django 3.1.1 on 2020-09-11 12:20

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_auto_20200609_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='name')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='proposals',
            name='categories',
            field=models.ManyToManyField(blank=True, to='app.ProposalCategory'),
        ),
    ]
